services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mehrwert\Phpmyadmin\Controller\PhpmyadminController:
    public: true

  Mehrwert\Phpmyadmin\Backend\PmaModule:
    public: true